// Auto-generated by scripts/write-mangled-property-names.mjs
// DO NOT EDIT — generated from mangled-whitelist.json
export default {
	"distinct_id": "a",
	"event": "b",
	"properties": "c",
	"timestamp": "d"
};
