name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Format check
        run: bun nx format:check

      - name: Lint
        run: bun nx run-many -t lint --all

      - name: Type check
        run: bun nx run-many -t typecheck --all

      - name: Test
        run: bun nx run-many -t test --all

      - name: Build
        run: bun nx run-many -t build --all
